runtime: python39  # Using Python to serve static files

handlers:
  - url: /(.*)
    static_files: build/web/\1
    upload: build/web/.*  # Ensure all web files are uploaded

  - url: /
    static_files: build/web/index.html
    upload: build/web/index.html
