name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  image_picker_for_web: any
  http: ^1.1.0
  google_fonts: ^6.2.1
  camera: ^0.11.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/eyeUp.png
    - assets/eyeDown.png
    - assets/eyeLeft.png
    - assets/eyeRight.png
